package com.mailwithpdf;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import com.common.ClsEncrypt;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
 
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.io.FileUtils;
import org.apache.struts2.ServletActionContext;

//import com.common.ClsEncrypt;
import com.connection.ClsConnection;

public class SendEmailAction {
	
	
 
		    
/*	    public String SendTomail(File saveFile,String formdetailcode,String recipient) throws IOException, AddressException,
	            MessagingException, SQLException {
	    	
	    	  String docnos="",subject="",message="",userName="",password="";
	    	  String host="",port="";
	        	 
	    	  EmailProcess ep=new EmailProcess();
	    	    Connection conn = null;
	    		HttpServletRequest request=ServletActionContext.getRequest();
	    		HttpSession session=request.getSession();
	    	
	    		
	    		//System.out.println("---------------------------in-----------");
	    		
	    		//System.out.println("==formdetailcode====="+formdetailcode);
	    		
	    		String msg="";
	    		String sub="";
	    		try {
	    			ClsConnection ClsConnection=new ClsConnection();

	    			conn=ClsConnection.getMyConnection();
					Statement stmt10 = conn.createStatement();
					 String strSql10 = "select msg,subject FROM gl_emailmsg where dtype='"+formdetailcode+"' ";
					  //	System.out.println("==strSql10===="+strSql10);
					  ResultSet rs10 = stmt10.executeQuery(strSql10);
					  while(rs10.next ()) {
					    
				
						  msg=rs10.getString("msg");
					
						  sub=rs10.getString("subject");
						 
						  //sub=" Autogenerated E-mail Testing";
					  
					            }
					  
					  stmt10.close();
					  conn.close();
		        }
					  catch(Exception e){
						  conn.close();
						  e.printStackTrace();
					  }
	    		
	    		
	    		
	    	 	docnos="1";
	    		 //recipient=request.getParameter("recipient");
	        	
	        	
	        	subject= sub;
	        	message=msg;
	        	 
	    	
	    	try{
	    	
	        File saveFile = null,uploadfile=null;
	        if(!(file==null)){
	        	
	        String tempPath = System.getProperty("java.io.tmpdir");
	        saveFile = new File(tempPath + File.separator + fileFileName);
	        FileUtils.copyFile(file, saveFile);
	        }
	        
try {
	ClsConnection ClsConnection=new ClsConnection();

	                 conn=ClsConnection.getMyConnection();
				Statement stmt1 = conn.createStatement();
				 String strSql1 = "select email,mailpass,smtpServer,smtpHostport FROM my_user where doc_no='"+session.getAttribute("USERID").toString()+"'";
				  //	System.out.println("==strSql1===="+strSql1);
				  ResultSet rs1 = stmt1.executeQuery(strSql1);
				  while(rs1.next ()) {
				    
			
					  userName=rs1.getString("email");
					  port=rs1.getString("smtpHostport");
					  host=rs1.getString("smtpServer");
					  password=rs1.getString("mailpass");
					  password=ClsEncrypt.getInstance().decrypt(password);
				 //System.out.println("getpassword====="+password);
				  
				  }
				  stmt1.close();
				  conn.close();
				  
	        }
				  catch(Exception e){
					  e.printStackTrace();
				  }

       System.out.println("===befor recipient EmailProcess"+recipient);
	        
	        ep.sendEmailwithpdf(host, port, userName, password, recipient,
	                subject, message, saveFile,docnos);
	 
	        if (saveFile != null) {
	            saveFile.delete();
	        }
	    	}
	    	catch(Exception e){
	    		e.printStackTrace();
	    		return "error";
	    	}
	 
	        return "success";
	    }*/
	 
 public String SendTomail(File saveFile,String formdetailcode,String recipient , String doc_no, String branch , String userid , String refid) throws IOException, AddressException,
        MessagingException, SQLException {
	
	  String docnos="",subject="",message="",userName="",password="";
	  String host="",port="";
		int auth=1;
	  EmailProcess ep=new EmailProcess();
	    Connection conn = null;
		HttpServletRequest request=ServletActionContext.getRequest();
		HttpSession session=request.getSession();
	
		
		//System.out.println("---------------------------in-----------");
		
	System.out.println("==formdetailcode====="+formdetailcode);
		
		String msg="";
		String sub="";
		try {
			ClsConnection ClsConnection=new ClsConnection();

			conn=ClsConnection.getMyConnection();
			Statement stmt10 = conn.createStatement();
			 String strSql10 = "select msg,subject FROM gl_emailmsg where dtype='"+formdetailcode+"' ";
			  //	System.out.println("==strSql10===="+strSql10);
			  ResultSet rs10 = stmt10.executeQuery(strSql10);
			  while(rs10.next ()) {
			    
		
				  msg=rs10.getString("msg");
			
				  sub=rs10.getString("subject");
				 
				  //sub=" Autogenerated E-mail Testing";
			  
			            }
			  
			  stmt10.close();
			  conn.close();
        }
			  catch(Exception e){
				  conn.close();
				  e.printStackTrace();
			  }
		
		
		
	 	docnos="1";
		 //recipient=request.getParameter("recipient");
    	
    	
    	subject= sub;
    	message=msg;
    	 
	
	try{
	
    /*File saveFile = null,uploadfile=null;
    if(!(file==null)){
    	
    String tempPath = System.getProperty("java.io.tmpdir");
    saveFile = new File(tempPath + File.separator + fileFileName);
    FileUtils.copyFile(file, saveFile);
    }*/
		ClsConnection ClsConnection=new ClsConnection();        
try {


             conn=ClsConnection.getMyConnection();
		Statement stmt1 = conn.createStatement();
		 String strSql1 = "select email,mailpass,smtpServer,smtpHostport FROM my_user where doc_no='"+session.getAttribute("USERID").toString()+"'";
		  //	System.out.println("==strSql1===="+strSql1);
		  ResultSet rs1 = stmt1.executeQuery(strSql1);
		  while(rs1.next ()) {
		    
	
			  userName=rs1.getString("email");
			  port=rs1.getString("smtpHostport");
			  host=rs1.getString("smtpServer");
			  password=rs1.getString("mailpass");
			  password=ClsEncrypt.getInstance().decrypt(password);
			  System.out.println("userName====="+userName);
			  System.out.println("port====="+port);
			  System.out.println("host====="+host);
		 System.out.println("getpassword====="+password);
		  
		  }
		  String strSqlauth = "select method FROM gl_config where field_nme='emailauth'";
		  ResultSet rs12 = stmt1.executeQuery(strSqlauth);
		  while(rs12.next ()) {
			  auth=rs12.getInt("method");
		  }
		  stmt1.close();
		  conn.close();
		  
    }
		  catch(Exception e){
			  e.printStackTrace();
		  }

		System.out.println("===befor recipient EmailProcess"+auth);
    
		 if(auth==0){
			 ep.sendEmailwithpdfNoAuth(host, port, userName,recipient,
			            subject, message, saveFile,docnos);  
			   
			   }
			   else
			   {
				   ep.sendEmailwithpdf(host, port, userName, password, recipient,
				            subject, message, saveFile,docnos);
			   }

	conn=ClsConnection.getMyConnection();
	Statement stmt10 = conn.createStatement();
	
	/*Inserting into emaillog*/
	String sqls=("insert into emaillog (doc_no, brhId, dtype, edate, userId, refid, email) values ('"+doc_no+"','"+branch+"','"+formdetailcode+"',now(),'"+userid+"','"+refid+"','"+recipient+"')");
	int datas = stmt10.executeUpdate(sqls);
	/*Inserting into emaillog Ends*/
	  
	  
    /*if (saveFile != null) {
        saveFile.delete();
    }*/
	}
	catch(Exception e){
		e.printStackTrace();
		return "error";
	}

    return "success";
}

	  
}
